### ISSUE TITLE
Determine root cause of CNCF failure when running against k8s version >=1.11

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-kubernetes#122]
CNCF tests are running properly with k8s 1.10 but have one failure with 1.11 & 1.12.

**Comment by spisarski** [comment]
see https://kubernetes.io/docs/tutorials/stateless-application/guestbook/ WRT the failing CNCF test

**Comment by Sanjhana-Jayagopal** [comment]
Referred the above link to manually deploy the Guestbook application. The pods and services were successfully deployed but I was not able to access the Cluster IP of the frontend to start/view the Guestbook app, i.e., could not get the "Viewing the Frontend Service via NodePort" step from the documentation to work.

**Comment by sbhojpur** [comment]
Please let me know the cluster your are using, i just tried it here locally and it works on 1.11.
Check if  kube-dns pods are running in your cluster.

Let me know the cluster/lab your are working on, i will have a look once

**Comment by spisarski** [comment]
@sbhojpur - user pass to all k8s pods running on Openstack should be ubuntu/Pa$$w0rd

**Comment by sbhojpur** [comment]
@spisarski , @Sanjhana-Jayagopal   
I just check lab3 and it seems to be working. 
Just did a curl with 'master IP : nodeport' and i can see the html page. The same works with minion IP as well, so NodePort is working.

I was no able to open browser session with cable labs, some connectivity issue with it but it should work for you.

**Comment by Sanjhana-Jayagopal** [comment]
Yes, it seems to be working when the guestbook application is deployed manually. However, with respect to the conformance tests, the logs(~/results/plugins/e2e/results/e2e.log) suggest that -
**** Failed to get response from guestbook. err: <nil>, response: <br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'No route to host [tcp://redis-slave:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:155****

**Comment by spisarski** [comment]
Tests are now executing properly with 1.11 on the 'refactor_and_cleanup' branch
