### ISSUE TITLE
Fix sonobuoy integration tests

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-kubernetes#202]
Just noticed on 4/9/2019 that the generation of the sonobuoy  pod descriptor is failing.

**Comment by RandyLevensalor** [comment]
Here are some of the changes that are needed.
[ ] Install Go 1.12 or later.  An older version is being installed.
[ ] Don't use sudo to install go or sonobuoy, it isn't needed.  Just install in local directory.
[ ] Don't terminate the script until after the test has completed.  Possibly use `sonobuoy run --wait`

See https://github.com/heptio/sonobuoy for me details.

**Comment by RandyLevensalor** [comment]
Go does not need to be installed when using compiled releases of Sonobuoy.
