### ISSUE TITLE
Deployments where nodes have multiple NICs have encountered certificate issues.

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-kubernetes#245]
This was found when creating the snaps-hyperbuild CI scripts. We were able to get around it by not configuring other network interfaces.

The error was:

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "--kubeconfig=/tmp/snaps-k8s-projects/snaps-hb-ci-boq/node-kubeconfig.yaml", "label", "nodes", "node-1", "zone=node-1"], "delta": "0:00:00.108842", "end": "2019-08-20 16:41:01.863203", "msg": "non-zero return code", "rc": 1, "start": "2019-08-20 16:41:01.754361", "stderr": "Unable to connect to the server: x509: certificate is valid for 10.241.0.1, 10.0.3.11, 10.0.3.11, 10.241.0.1, 127.0.0.1, 10.0.3.11, not 10.0.1.11", "stderr_lines": ["Unable to connect to the server: x509: certificate is valid for 10.241.0.1, 10.0.3.11, 10.0.3.11, 10.241.0.1, 127.0.0.1, 10.0.3.11, not 10.0.1.11"], "stdout": "", "stdout_lines": []}

Guess either the certificate needs to be generated for the 10.0.1 network, or we use 10.0.3 network in k8s config.
also see https://github.com/cablelabs/openhw-hyperbuild/issues/243

**Comment by spisarski** [comment]
see the branch 'kubectl-build-config-multi-nic' for work in progress

**Comment by bo-quan** [comment]
re-open as it is not resolved yet.
