### ISSUE TITLE
Add CNCF tests to CI

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-kubernetes#59]
https://kubernetes.io/blog/2017/10/software-conformance-certification/
https://github.com/cncf/k8s-conformance

**Comment by Sanjhana-Jayagopal** [comment]
Progress on the automation of conformance tests. Everything on our end seems to be working for now, but there is some issue with the sonobuoy image that is to be downloaded. Found many other users reporting the same issue on their slack channel. The sonobuoy team is working on fixing it.

**Comment by spisarski** [comment]
The 'refactor_and_cleanup' branch is now executing the tests, we just now need to add in a timeout polling mechanism to know when the tests have completed, extract the results archive file and parse the e2e.logs to determine if all tests passed.

**Comment by spisarski** [comment]
Also add a switch in the CI job's env file to turn the CNCF tests on/off

**Comment by spisarski** [comment]
One can optionally execute the CNCF certification tests when running CI. Checking and submitting the results can remain a manual process.
