### ISSUE TITLE
Use Ansible apt task to install packages

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-kubernetes#71]
We do not need to call apt-get install package from Ansible.  Several packages can be combined into out task.

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-dev
        - libffi-dev
        - gcc
        - libssl-dev
        - python-selinux
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - libltdl7
        - aufs-tools
        - network-manager
        - crudini

**Comment by spisarski** [comment]
This has been performed in setup_k8.yaml; however, I will use this task for installing the prerequisites which is currently occurring within iaas_launch.py via command calls.
