### ISSUE TITLE
Install Guide Updates

### ISSUE THREAD

**Issue by chriscorcimiglia** [cablelabs/snaps-kubernetes#79]
This is per the notes provided in PR #70. 

Two main issues need to be addressed with the install guide:

1. Remove any references to the "sample config template" in snaps_k8s/k8s-deploy.yamle. This file should really never be used or altered

2. Streamline the build host setup. There isn't much other than python and sshpass (for which I'd like to see removed eventually) that is really necessary and ensure that the Python runtime is installed.

Also for section 4.1.3, really only need to install the following from apt:

 - git
 - sshpass
 - optionally python-pip (for pip install above)

Finally, please see the CI build script for how to install that can be found at: `snaps-kubernetes/ci/playbooks/deploy_k8.yaml` The install guide should be aligned with this.

**Comment by spisarski** [comment]
Docs should be properly updated
