### ISSUE TITLE
Hostname and kubernetes hostnames cannot have uppercase characters

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-kubernetes#94]
When a hostname begins with a capital ascii letter, it is transformed to lowercase as a k8s host which can cause issues downstream. Sorry, I had not captured those logs but it is easy to recreate by simply changing your snaps-boot hosts.yaml and references in your k8s deployment.yaml files to start with uppercase letters.

**Comment by chiraggupta06** [comment]
A Pull request #98 has been created.

Regards,
Chirag Gupta
